/// Static template assets generated programmatically by post_gen.dart.
///
/// Storing these in hook assets rather than inside `__brick__/` prevents
/// Mason from failing on Windows during `mason get` / `mason upgrade` due to
/// dot-directory traversal and wildcard path expansion (`references\*`).

const Map<String, String> harnessFiles = {
  'active-context.md': r'''# Active Context

<!-- Updated by AI agents after each task. Max 5 entries in Recent Tasks. -->
<!-- Rule: every "Done" MUST include proof (commit:hash or file:path). -->

## Current Focus
_None yet — first agent session._

## Recent Tasks
_No tasks completed yet._

## Key Decisions
_No decisions recorded yet._

## Known Issues
_None._
''',
  'progress.md': r'''# Progress Log

<!-- Append-only. Never auto-loaded by agents. Read on-demand only. -->
<!-- Format: [YYYY-MM-DD] task description (proof: commit:hash or file:path) -->
''',
};

const Map<String, String> skillFiles = {
  'SKILL.md': r'''---
name: flutter-senior-dev
description: Acts as a senior Flutter developer for projects built on the Flutter-RxDart-Base architecture (Redux for session state, one RxDart BLoC per screen, Dio with a 5-interceptor chain, Mason bricks project/bloc/harness, wire_route.dart, redux_rxdart_lints). Use whenever the user is planning, designing, reviewing or scaffolding Flutter work on this stack - feature breakdowns, phase or roadmap planning, screen and user-flow design, user-journey documents, architecture decisions, code review, "how should we build X in Flutter", or any mention of AppStore, ApiBaseHelper, ApiResponse, CancelTokenOwner, golden rules, mason make bloc or AGENTS.md - even if they never name this skill. Do not use for non-Flutter work.
---

# Flutter senior dev (RxDart-Base)

Answer the way the team's senior Flutter developer would: pragmatic, opinionated, and focused on shipping with a low learning curve. The value of this skill is that plans and code fit the architecture the team already has, instead of drifting toward generic Flutter advice.

## Stance

- Default to what the base already provides. Propose a new package or tool only with a concrete reason, and state its cost (learning curve, migration, build size).
- Recommend, don't just list options. If you disagree with a request, say so once, constructively, with the reason, then help with what the user decides.
- Be honest about gaps in the base. Several LMS/ERP-style needs (offline queue, token refresh, streaming, tablets) are not covered out of the box; flag them early. See `references/base-gaps.md`.
- Verify before asserting. Exact signatures, file paths and behaviors must come from the repo (`AGENTS.md`, `architecture.md`, the real files), not from memory. If something is inferred, say so.

## Source of truth, in order

1. The project's own `AGENTS.md`, `architecture.md` and code.
2. `references/architecture.md` in this skill: a snapshot of the base as of harness brick 1.1.0.
3. If the public GitHub `main` and the user's working copy disagree, trust the working copy. Earlier snapshots of the base lacked the harness brick, the lint plugin and several UI components.

## The stack in one paragraph

Feature-first Flutter app generated by Mason bricks. Redux (`AppStore`) holds only session data that must survive restarts: `authToken`, `userData`, `locale`, persisted to SharedPreferences. Everything screen-scoped lives in a per-screen RxDart BLoC created in `initState()` and disposed in `dispose()`. Networking is Dio with HTTP/2 and a fixed interceptor chain (Connectivity, Auth, Platform, Retry, ErrorMap) behind `ApiBaseHelper`, which returns raw `Map<String, dynamic>` and throws a sealed `ApiException`. Navigation is Navigator with a `Routes` registry and `onGenerateRoute`. UI uses `flutter_screenutil`, design tokens in `ResColors`/`AppTypography`, and localization via `context.l10n` (en, hi).

## Golden rules (AGENTS.md is authoritative; this is the working summary)

1. Repository is transport only: call `ApiBaseHelper`, return the raw `Map`, never `Model.fromJson`.
2. BLoC owns business logic and state: await the repo, parse with `Model.fromJson`, catch errors, emit `ApiResponse<T>`; show `e.userMessage` in the UI.
3. Zero `setState` in widgets.
4. Zero RxDart outside BLoC: widgets consume plain `Stream<T>` / `ApiResponse<T>` only.
5. Rule of 2 for widgets: used in two places means extract to `utils/widgets/common/`; reuse with parameters before duplicating.
6. Standard `Scaffold`-based presentation unless a wrapper is requested.
7. Forms use controllers owned by the StatefulWidget and pass strings to BLoC methods.
8. Fetch pattern: `Future<void> fetch({bool refresh = false})`, call `createNewToken()` first; live search uses a `PublishSubject` with debounce 300 ms and `distinct()`.
9. One-off UI events (toast, navigation) go through a `PublishSubject` in the BLoC, subscribed in `initState()` and cancelled in `dispose()`.
10. Redux bridge: after a mutation changes session data, the UI dispatches to the store once the new model has rendered.
11. `AuthInterceptor` attaches the bearer token whenever one exists, including on public endpoints.
12. Defensive JSON parsing everywhere: null-safe numbers, strings, lists and dates with sensible defaults.

Rules 1, 3 and 4 are enforced at analyze time by `redux_rxdart_lints`. Say which rule a suggestion serves when it isn't obvious.

## Where does this live?

| Question | Answer |
|---|---|
| Must it survive restart and is it session data? | Redux (`authToken`, `userData`, `locale`). Extend `AppState` deliberately, never for screen state. |
| Screen data, form state, toggles, tabs | BLoC |
| Device or platform capability (push, GPS, scanner, native bridge) | `lib/services/` |
| Widget used in 2+ places | `lib/utils/widgets/common/` |
| Model used by 2+ features | shared models folder (propose `lib/shared/models/` the first time it happens) |
| Permission checks | Derived from `userData` through one helper; UI hides or disables, the backend is the authority |
| Route added | `Routes` constant plus a case in `AppRouter`, done by `wire_route.dart` |

## Workflows

**Scaffold a feature.** Run `dart run scripts/agent/wire_route.dart <feature_name> [route_path]` (scaffolds via `mason make bloc` if missing, then wires the route). Without the harness, run `mason make bloc` and wire the route by hand. Then fill in repo, BLoC, model and widgets, and run `./scripts/agent/verify.sh` (or `verify.ps1` on Windows). The gate is `dart format --set-exit-if-changed .` plus `flutter analyze --fatal-infos`.

**Review code.** Check the twelve rules first, then: emissions guarded with `isClosed`, `createNewToken()` before requests, `cancelRequests()` and `subscriptions.dispose()` in `dispose()`, `$` suffix on public streams, no hardcoded pixel sizes (use `.w .h .r .sp`), strings through l10n, errors mapped through `userMessage`, and no screen state leaking into Redux.

**Plan features, phases, screens or user journeys.** Read `references/planning-checklist.md` and follow it. Default to its neutral mode: describe who does what and what the system must handle, and do not assume navigation patterns (drawer, tabs), screen names, app topology or which surface hosts a step. Raise those as open decisions unless the user has decided them. Treat a user's hypothetical as a question, not a decision.

**Extend the base.** Read `references/base-gaps.md` before proposing anything that touches networking, Redux or the interceptor chain.

## Do and don't

- Don't introduce Riverpod, go_router, freezed, GetIt or a monorepo tool unless the user asks or the need is clear and costed. go_router and auto_route in particular break `wire_route.dart`.
- Don't commit unprompted. Commit only when the user explicitly asks, using Conventional Commits (`feat(scope): ...`, `fix(scope): ...`) with the rationale.
- Use only the canonical repository URL from the project's `CONTRIBUTING.md` when writing git URLs. If the working remote differs, ask before writing a new URL.
- When changing a brick, follow `CONTRIBUTING.md`: bump the brick version, update its CHANGELOG, and update READMEs in the same change. A Golden Rule change that can be enforced mechanically must be mirrored in the lint plugin.
- Keep answers proportionate: short for simple questions, structured documents only when asked for one.

## Keeping this skill in sync

This skill summarizes `AGENTS.md` and `architecture.md`. When the golden rules, the interceptor chain, the Redux shape or the brick outputs change, update `references/architecture.md` and the rule summary above in the same change, so the skill does not drift from the repo.
''',
  'references/architecture.md':
      r'''# Base architecture snapshot (harness brick 1.1.0)

Contents: 1 Generated layout, 2 Networking, 3 Redux, 4 BLoC and page lifecycle, 5 UI kit, 6 Routing, 7 Localization and sizing, 8 Bricks, harness and lints, 9 Dependencies.

This is a summary of the base repository. If the working copy differs, the working copy wins. Re-read the real file before quoting a signature.

## 1. Generated layout (`mason make project`)

```
AGENTS.md / CLAUDE.md          # harness: agent contract (CLAUDE.md = @AGENTS.md)
scripts/agent/                 # wire_route.dart, verify.ps1, verify.sh
lib/
├── features/                  # one folder per screen/flow (bloc brick output)
├── l10n/                      # app_en.arb, app_hi.arb  (l10n.yaml at project root)
├── networking/
│   ├── interceptors/          # connectivity, auth, platform_injector, error_mapping
│   ├── api_base_helper.dart   # facade: get/post/put/delete/postFormData/putFormData
│   ├── api_constants.dart     # base URL and endpoint registry
│   ├── api_exceptions.dart    # sealed ApiException (8 subtypes)
│   ├── api_response.dart      # sealed ApiResponse<T>
│   ├── cancel_token_owner.dart
│   └── dio_client.dart
├── redux/                     # actions, app_state, app_store, reducers/, middleware/
├── resources/                 # res_colors.dart, app_typography.dart
├── services/                  # notification_service, device_info_service (stubs)
├── screens/                   # showcase demo
├── utils/                     # extensions/, router/, widgets/, common_utils, show_message
└── main.dart
```

Feature folder from `mason make bloc`:

```
lib/features/<name>/
├── bloc/<name>_bloc.dart
├── model/                      # empty, .gitkeep
├── repo/<name>_repo.dart
├── widgets/<name>_content_widget.dart
└── <name>_page.dart
```

## 2. Networking

- `DioClient` singleton: base URL from `ApiConstants`, 30 s connect/receive/send timeouts, JSON, HTTP/2 adapter.
- Interceptor order (do not reorder): 1 Connectivity (blocks when offline), 2 Auth (bearer from `AppStore.authToken`), 3 PlatformInjector (adds `{"platform": "app"}` to JSON bodies), 4 Retry (`dio_smart_retry`, 3 retries at 1 s, 2 s, 4 s on timeouts and 502/503), 5 ErrorMapping.
- `ApiBaseHelper({Dio? dio})` is constructible for tests and has a lazy `instance` singleton. Methods return `Future<Map<String, dynamic>>` and throw `ApiException`. Each accepts `queryParameters` and `cancelToken`; the form-data variants accept `onSendProgress`. A response whose top level is not a JSON object throws at the cast, so list endpoints must be wrapped in an object or need an extra method.
- Repositories take `{ApiBaseHelper? api}` and default to `ApiBaseHelper.instance`.
- `ApiException` (sealed): `NoInternetException`, `BadRequestException` (400), `UnauthorizedException` (401), `NotFoundException` (404), `ConflictException` (409), `RequestTimeoutException` (408 or Dio timeouts), `InternalServerErrorException` (500 and fallbacks), `BusinessLogicException` (HTTP 200/201 with `{"status": false, "message": ...}`).
- Only `BusinessLogicException.message` is shown verbatim to users. Everything else maps through `userFacingMessage` / `userMessage` (extension in `utils/extensions/exception_ext.dart`), which has a switch with safe copy.
- `ApiResponse<T>` (sealed): `Initial`, `Loading`, `Completed(data)`, `Error(error, {retry})`; `.data` returns data only when completed.
- `CancelTokenOwner` mixin: `cancelToken` (lazy), `isCancelled`, `cancelRequests([reason])`, `createNewToken()` (cancels the old one, creates a fresh one).

## 3. Redux (session only)

- `AppState` fields: `authToken`, `userData` (a `Map<String, dynamic>?`), `locale`. Immutable with `copyWith`.
- `AppAction` sealed: `SetAuthTokenAction`, `SetUserDataAction`, `SetLocaleAction`, `LogoutAction`. Reducer uses exhaustive switch.
- `AppStore.init()` hydrates from SharedPreferences (`auth_token`, `locale`, `user_data`) and must be awaited in `main()` before `runApp` so no request goes out unauthenticated. `AppStore.authToken`, `AppStore.state`, `AppStore.dispatch(...)` are static helpers for non-widget code.
- Middleware: `loggingMiddleware` (debug) and `persistenceMiddleware` (writes to SharedPreferences).
- The token is stored in plain SharedPreferences. Flag this for any app handling minors' or financial data.

## 4. BLoC and page lifecycle

- `final class XBloc with CancelTokenOwner`, constructor `XBloc({XRepo? repo})`, a `CompositeSubscription subscriptions`, and `void dispose()` that calls `cancelRequests()` and `subscriptions.dispose()`.
- Public streams end in `$` (`state$`, `data$`). `BehaviorSubject` for state, `PublishSubject` for one-off events. Guard every emission after an `await` with `if (!subject.isClosed)`.
- Page: `StatefulWidget`, `late final XBloc _bloc` created in `initState()`, disposed in `dispose()`. The page hosts the BLoC; the content widget is "dumb" and takes data.
- Pattern A (search/fetch/events) and Pattern B (forms, Redux bridge) are rules 7 to 10 in the golden rules.

## 5. UI kit (`utils/widgets/`)

`AppScaffold`, `AppCard`, `AppResponseBuilder<T>` (binds an `ApiResponse` stream to loading, error-with-retry, and a typed builder), `AppLoadingState`, `AppErrorState`, `AppEmptyState`, `CommonButton` (built-in loading spinner), `AppTextFormField` (label, hint, password toggle), `AppDialog` (`showConfirmation`, `showStatus`, `showAsyncConfirm`). Toasts via `ShowMessage.success/error/info/warning` (OverlaySupport). Helpers in `CommonUtils` (hideKeyboard, launcher recipes, showCommonDialog).

## 6. Routing

Navigator with `onGenerateRoute` in `utils/router/app_router.dart`, constants in `utils/router/routes.dart` (`abstract final class Routes`), and a `navigatorKey`. `wire_route.dart` adds a `Routes` constant and a `switch (settings.name)` case, supports delegated sub-routers whose filename contains the route prefix, and refuses to inject when `go_router` or `auto_route` is in `pubspec.yaml`.

## 7. Localization and sizing

`l10n.yaml` points at `lib/l10n` with `app_en.arb` as template; generated class `AppLocalizations` in `lib/l10n/generated`. Access via `context.l10n`; theme text via `context.textTheme`. Use `flutter_screenutil` units (`.w .h .r .sp`) instead of raw pixels. Designed for phones; tablets and desktop web need their own design size or layout.

## 8. Bricks, harness and lints

- `project`: run once on a fresh `flutter create` from inside the app folder (the hook checks for `android/` and `ios/`, then runs `flutter pub get`, `flutter gen-l10n`, package rename, and optionally the harness).
- `bloc`: run per feature from the project root; auto-detects `project_name` from `pubspec.yaml`.
- `harness`: writes `AGENTS.md`, `CLAUDE.md`, `scripts/agent/*`, and wires `custom_lint` plus `redux_rxdart_lints` (git dependency) into `pubspec.yaml` and `analysis_options.yaml`.
- Lint rules: `no_rxdart_in_ui` (rule 4), `no_setstate_in_widget` (rule 3), `repo_transport_only` (rule 1).
- Quality gate: `dart format --set-exit-if-changed .` and `flutter analyze --fatal-infos`.
- Backend discovery convention: look for `*.postman_collection.json` first, then OpenAPI/Swagger, then docs.

## 9. Key dependencies

dio, dio_smart_retry, dio_http2_adapter, connectivity_plus, redux, flutter_redux, shared_preferences, rxdart, flutter_screenutil, overlay_support, intl, url_launcher, snug_logger; dev: flutter_lints, change_app_package_name, custom_lint, redux_rxdart_lints.
''',
  'references/base-gaps.md': r'''# Base gaps and extension recipes

Contents: 1 Security and session, 2 API contract, 3 Offline, 4 Permissions and modules, 5 Forms and shared models, 6 Devices and form factors, 7 Streaming and AI, 8 Tenancy, 9 Changing the base safely.

These are the places where the base, as shipped, does not cover what larger LMS/ERP-style apps need. Raise them early, in the phase where they first bite, and keep each fix small and inside the golden rules.

## 1. Security and session

- **Token storage.** The token is persisted in plain SharedPreferences. For apps holding minors' or financial data, move the token to `flutter_secure_storage`: change `AppStore.init` and `persistence_middleware`, keep the rest of `AppState` where it is.
- **Refresh flow.** `AuthInterceptor` only injects the token, and `AppState` has no refresh token. Add `refreshToken` to state and actions, then on a 401 refresh once and retry, or dispatch `LogoutAction` and route to sign-in. Put the interceptor before the retry step and avoid refresh loops (single in-flight refresh, no refresh on the refresh call).
- **Other controls.** Certificate pinning, root/jailbreak detection and screenshot blocking for exam and finance screens are native concerns behind a service in `lib/services/`. Never log PII; `snug_logger` output and the Redux logging middleware are debug only.

## 2. API contract

- Responses must be JSON objects. Either the backend wraps lists (`{"items": [...]}`) or add a `getList` method to `ApiBaseHelper`.
- Business errors are `{"status": false, "message": ...}` with HTTP 200/201; that message is shown verbatim, so it must be safe, localized copy.
- `PlatformInjectorInterceptor` adds `{"platform": "app"}` to every JSON body. Confirm the backend expects it, or remove it.
- Agree pagination (cursor or page), sorting and filter conventions, an API version header, and an idempotency key for payments and other writes.

## 3. Offline

`ConnectivityInterceptor` rejects requests when offline, which is right for reads and wrong for queued writes. For offline-first features such as attendance: add a local store (sqflite or Drift) and a queue service in `lib/services/`, let the BLoC write to the queue and the service replay it when connectivity returns, define conflict rules per entity (last write wins vs server wins with a review), and show queued and failed items in the UI. Decide the store at the start of the phase that needs it, not earlier.

## 4. Permissions and modules

- Keep role, permissions and enabled-module flags inside `userData`; do not add fields to Redux for this. Add one `Can(permission)` helper in `utils/` (with a field-level variant) and use it for both visibility and disabled states. The backend still enforces.
- Drawer and tab entries come from one module list (`lib/modules.dart`) filtered by `Can()` and the tenant's enabled modules. Routes stay wired by `wire_route.dart`. If a module must be absent from a binary, give it its own delegated router and a separate entry point or flavor.

## 5. Forms and shared models

- Server-driven forms need dynamic fields without `setState`: a `DynamicFormBloc` exposes `values$` and validation state, the widget owns a map of controllers and disposes them, and the field renderers live in `utils/widgets/common/`.
- The first time two features need one model, create `lib/shared/models/`. Features never import other features.

## 6. Devices and form factors

`flutter_screenutil` is set up for phones. Kiosk and tablet screens (POS, invigilator) need their own design size or adaptive layout, and dense desktop tables are a poor fit; treat a web admin console as a separate decision. Background GPS and scanners need real-device testing (battery optimization, permissions) and live in `lib/services/`.

## 7. Streaming and AI

`ApiBaseHelper` has no streaming call. Add one using Dio `ResponseType.stream` that returns a `Stream<String>` chunk stream, and let the BLoC turn it into `ApiResponse` states. Keep "AI drafts, humans approve" visible in the UI: drafts are labelled, approval goes through the normal workflow, and PII is redacted on the client before anything is sent.

## 8. Tenancy

Branding, locale, grading and date formats vary per institution. Load tenant config at bootstrap and keep it out of widget code (tokens in `ResColors`, formats behind helpers). Start with per-flavor config; move to runtime tenant config only when one build must serve several tenants.

## 9. Changing the base safely

Follow the project's `CONTRIBUTING.md`: bump the affected brick version and CHANGELOG, update READMEs in the same change, mirror any mechanically enforceable golden rule in `redux_rxdart_lints`, run format and analyze from each touched package directory, dry-run any `wire_route.dart` or hook injection change against real templates, and commit only when asked.
''',
  'references/planning-checklist.md':
      r'''# Planning checklist: features, flows and journeys

Contents: 1 Method, 2 Per-screen questions (design mode), 3 Per-flow template, 4 Journey table, 5 Surfaces and design decisions, 6 Cross-cutting topics, 7 Document structure, 8 Quality bar.

Use this when turning a requirements or roadmap document into plans: user flows, user journeys, and the things a senior dev must think through.

**Two modes.** Default to **neutral mode**: describe who does what, in what order, what the system must do, and what can go wrong. Do not choose navigation patterns (drawer, tabs), screen names, app topology, which surface (mobile app, web console) hosts a step, or architecture. List those as open decisions with options and why they matter, without a recommended default, unless the user asks for one. Switch to **design mode** (screens, feature folder names, navigation) only when the user has said those decisions are made or asks for them. A hypothetical from the user ("if I had a drawer with four modules...") is a question, not a decision.

## 1. Method

1. Extract roles first. List every persona and the device, connectivity and permission context it works in. Design role-based screens rather than exposing every feature to every user.
2. Describe each module by what users need to do and what the system does. Do not assign steps to a surface (mobile app, web console, backend) unless the user decided; raise it as an open decision.
3. Design mode only: name features in `snake_case` as they would appear under `lib/features/`, one per screen or flow.
4. Walk each journey step by step: actor, surface, screen, system response, failure paths.
5. Collect the backend contract and base-gap implications as you go, then list open decisions with a recommended default.

## 2. Per-screen questions

- Who can open it, and which fields are visible or editable per role (field-level)?
- What are its states: loading, empty, error with retry, offline, stale data, no permission, partial success?
- Which endpoints does it call, and is each idempotent? What does a duplicate tap or a retry do?
- What happens on a 401, on `status: false`, on a timeout, on slow networks?
- Does it need offline reads or offline writes? If writes, what is the queue and the conflict rule?
- Does it hold sensitive data (minors, grades, health or wellbeing, finance, ID documents)? What must never reach logs, screenshots or the clipboard?
- How is it reached: drawer or tab, deep link from a notification, QR or NFC, another screen?
- What does it emit for notifications, analytics and audit correlation?
- Localization: strings via `context.l10n`, plural and date/number formats, and RTL if the tenant needs it.
- Accessibility: screen reader labels, text scaling, contrast, touch target size.
- Form factor: phone only, or tablet and kiosk?
- Test level: BLoC unit tests with a mocked repo, widget test for the content widget, and which journey covers it end to end.

## 3. Per-flow template

```
Flow: <name>
Actors: <roles>
Trigger: <what starts it>
Preconditions: <identity, permission, data state>
Happy path: 1 ... 2 ...
Alternate and failure paths: <offline, denied, validation, conflict, timeout>
Data involved: <information created, read or changed>
Notifications and audit: <what fires>
Open questions: <decisions needed>
```

## 4. Journey table

Use one table per journey with these columns (neutral mode):

| # | Actor | What happens | Rules and edge cases |

In design mode, add Surface and Screen or feature columns.

Keep steps at the level a QA engineer could turn into an end-to-end test.

## 5. Surfaces and design decisions

Do not assume where a step happens. Whether something lives in a mobile app, a web or back-office interface, or only in the backend is a scope decision for the team. In neutral mode, say who acts and what the system does, and add the surface question to the open-decisions list (with options and why it matters). Record any surface split you do propose as a proposal, and only when asked.

## 6. Cross-cutting topics to cover in any plan

Navigation and role routing; session lifecycle (bootstrap, expiry, logout, multi-device); permissions; tenancy, branding and localization; offline and sync; notifications and deep links; documents and uploads (size, type, progress, resume); payments (pending and failed states, idempotency, receipts, reconciliation); security and privacy (token storage, screenshot and root protection for exams and finance, PII in logs, children's data consent and retention, restricted wellbeing data); accessibility; performance on low-end Android (startup, memory, app size budgets); observability (crash reporting, analytics, audit correlation IDs); error contract with the backend; testing and release (flavors, staged rollout, feature flags); data migration and versioning of APIs.

## 7. Document structure for a user-flow and journey document (neutral mode)

1. How to read this document: purpose, what it does not decide, conventions, source.
2. Roadmap or scope at a glance.
3. Users and roles (what each needs to do; one person may hold several roles).
4. Foundation flows: who, what happens, rules and edge cases.
5. Capabilities by phase, taken from the source.
6. End-to-end journeys (one table each).
7. Situations every flow should handle.
8. Cross-cutting considerations.
9. Integration and data agreements to settle with the backend.
10. Open decisions (options and why they matter, no recommended default).
11. Appendix: glossary and traceability to the source.

Mark anything not in the source (edge cases, examples) as suggestions for the team to confirm.

## 8. Quality bar

- In design mode, every feature name maps to something a developer can scaffold.
- Every flow has failure paths, not only the happy path.
- Assumptions are labelled as assumptions; the source document's wording is not silently changed.
- Open decisions list options and why they matter. Add a recommended default only when the user asks for one.
''',
};
